os:
- linux
- osx

dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
    - lynx
    - sqlite3
    - libsqlite3-dev
    - libboost-system-dev
    - libboost-filesystem-dev
    - libboost-dev
    - pkg-config
    - libpangomm-1.4-dev
    - libcairomm-1.0-dev
    - python-xattr
    - acl
language: cpp
compiler:
- gcc
- clang

matrix:
  exclude:
  - os: osx
    compiler: gcc

install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pangomm; fi

# glibmm currently uses deprecated std::auto_ptr<>, hence flags.
script:
- ./autogen.sh
- if [[ "$TRAVIS_OS_NAME" == "linux" && "$CC" == "gcc" ]]; then CXXFLAGS_EXTRA="-Wno-error=deprecated-declarations" ./configure CC=gcc-6 CXX=g++-6 ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" && "$CC" == "clang" ]]; then ./configure; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then CXXFLAGS_EXTRA="-Wno-error=c++14-extensions" ./configure ; fi
- make
- VERBOSE=true make check
