dist: trusty
sudo: required
language: cpp
compiler:
- clang
- gcc

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq lynx sqlite3 libsqlite3-dev libboost-system-dev libboost-filesystem-dev libboost-dev pkg-config libpangomm-1.4-dev libcairomm-1.0-dev

script:
- ./autogen.sh
- ./configure
- make
- VERBOSE=true make check
